#!/bin/zsh
aws cloudfront create-invalidation \
  --distribution-id file://devops/aws:cloudfront/distribution-id \
  --invalidation-batch "Paths={Quantity=1,Items=["/v3.json"]},CallerReference=`uuidgen`"
